/**
 * AntharikshAI - Mindmap Export Utility
 * Simplified for reliability
 */

import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

/**
 * Captures mindmap as image
 */
export const captureMindmap = async (element, options = {}) => {
    if (!element) {
        return { success: false, error: 'No element provided' };
    }

    try {
        const canvas = await html2canvas(element, {
            scale: 2,
            backgroundColor: options.backgroundColor || '#0a0a0f',
            logging: false
        });

        return { success: true, canvas };
    } catch (err) {
        console.error('Capture error:', err);
        return { success: false, error: err.message };
    }
};

/**
 * Downloads mindmap as PNG
 */
export const downloadAsPNG = async (element, filename, options = {}) => {
    const result = await captureMindmap(element, options);
    
    if (!result.success) {
        return result;
    }

    try {
        const link = document.createElement('a');
        link.download = `${filename.replace(/\s+/g, '_')}_mindmap.png`;
        link.href = result.canvas.toDataURL('image/png');
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        return { success: true };
    } catch (err) {
        return { success: false, error: err.message };
    }
};

/**
 * Downloads mindmap as PDF
 */
export const downloadAsPDF = async (element, filename, options = {}) => {
    const result = await captureMindmap(element, options);
    
    if (!result.success) {
        return result;
    }

    try {
        const canvas = result.canvas;
        const imgData = canvas.toDataURL('image/png');
        
        const pdf = new jsPDF({
            orientation: 'landscape',
            unit: 'mm',
            format: 'a4'
        });

        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();
        
        // Add watermark
        if (options.showWatermark !== false) {
            pdf.setFontSize(10);
            pdf.setTextColor(200, 200, 200);
            pdf.text('Generated by AntharikshAI', pageWidth - 50, pageHeight - 10);
        }
        
        // Add title
        pdf.setFontSize(16);
        pdf.setTextColor(0, 0, 0);
        pdf.text(`${filename} - Mindmap`, 10, 10);
        
        // Add image
        const imgWidth = pageWidth - 20;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        pdf.addImage(imgData, 'PNG', 10, 20, imgWidth, Math.min(imgHeight, pageHeight - 30));
        
        pdf.save(`${filename.replace(/\s+/g, '_')}_mindmap.pdf`);
        
        return { success: true };
    } catch (err) {
        return { success: false, error: err.message };
    }
};

/**
 * Main export function
 */
export const exportMindmap = async (element, chapterName, format, options = {}) => {
    if (format === 'png') {
        return await downloadAsPNG(element, chapterName, options);
    } else if (format === 'pdf') {
        return await downloadAsPDF(element, chapterName, options);
    }
    return { success: false, error: 'Invalid format' };
};

export default {
    captureMindmap,
    downloadAsPNG,
    downloadAsPDF,
    exportMindmap
};
