// Central syllabus data for both Chat.jsx and Admin Materials uploader.
// Keep this in sync with src/pages/Chat.jsx.

export const syllabusData = {
  CBSE: {
    "8": {
      "MATHEMATICS": [
        "Rational Numbers",
        "Linear Equations in One Variable",
        "Understanding Quadrilaterals",
        "Practical Geometry",
        "Data Handling",
        "Squares and Square Roots",
        "Cubes and Cube Roots",
        "Comparing Quantities",
        "Algebraic Expressions and Identities",
        "Visualising Solid Shapes",
        "Mensuration",
        "Exponents and Powers",
        "Direct and Inverse Proportions",
        "Factorisation",
        "Introduction to Graphs",
        "Playing with Numbers",
      ],
      "SCIENCE": [
        "Crop Production and Management",
        "Microorganisms: Friend and Foe",
        "Synthetic Fibres and Plastics",
        "Materials: Metals and Non-Metals",
        "Coal and Petroleum",
        "Combustion and Flame",
        "Conservation of Plants and Animals",
        "Cell – Structure and Functions",
        "Reproduction in Animals",
        "Reaching the Age of Adolescence",
        "Force and Pressure",
        "Friction",
        "Sound",
        "Chemical Effects of Electric Current",
        "Some Natural Phenomena",
        "Light",
        "Stars and the Solar System",
        "Pollution of Air and Water",
      ],
      "HISTORY": [
        "How, When and Where",
        "From Trade to Territory",
        "Ruling the Countryside",
        "Tribals, Dikus and the Vision of a Golden Age",
        "When People Rebel",
        "Colonialism and the City",
        "Weavers, Iron Smelters and Factory Owners",
        "Civilising the Native, Educating the Nation",
      ],
      "GEOGRAPHY": [
        "Resources",
        "Land, Soil, Water, Natural Vegetation and Wildlife",
        "Mineral and Power Resources",
        "Agriculture",
        "Industries",
        "Human Resources",
      ],
      "CIVICS": [
        "The Indian Constitution",
        "Understanding Secularism",
        "Why Do We Need a Parliament",
        "Understanding Laws",
        "Judiciary",
        "Understanding Our Criminal Justice System",
        "Understanding Marginalisation",
        "Confronting Marginalisation",
      ],
      "ENGLISH": [
        "The Best Christmas Present in the World",
        "The Tsunami",
        "Glimpses of the Past",
        "Bepin Choudhury’s Lapse of Memory",
        "The Summit Within",
        "This Is Jody’s Fawn",
        "A Visit to Cambridge",
        "A Short Monsoon Diary",
      ],
      "HINDI": [
        "ध्वनि",
        "लाख की चूड़ियाँ",
        "बस की यात्रा",
        "दीवानों की हस्ती",
        "चिट्ठियों की अनूठी दुनिया",
        "भगवान के डाकिए",
        "क्या निराश हुआ जाए",
        "यह सबसे कठिन समय नहीं",
      ],
    },
    "9": {
      "MATHEMATICS": [
        "Number Systems",
        "Polynomials",
        "Coordinate Geometry",
        "Linear Equations in Two Variables",
        "Introduction to Euclid’s Geometry",
        "Lines and Angles",
        "Triangles",
        "Quadrilaterals",
        "Areas of Parallelograms and Triangles",
        "Circles",
        "Constructions",
        "Heron’s Formula",
        "Surface Areas and Volumes",
        "Statistics",
        "Probability",
      ],
      "SCIENCE": [
        "Matter in Our Surroundings",
        "Is Matter Around Us Pure",
        "Atoms and Molecules",
        "Structure of the Atom",
        "The Fundamental Unit of Life",
        "Tissues",
        "Diversity in Living Organisms",
        "Motion",
        "Force and Laws of Motion",
        "Gravitation",
        "Work and Energy",
        "Sound",
        "Why Do We Fall Ill",
        "Natural Resources",
        "Improvement in Food Resources",
      ],
      "HISTORY": [
        "The French Revolution",
        "Socialism in Europe and the Russian Revolution",
        "Nazism and the Rise of Hitler",
        "Forest Society and Colonialism",
        "Pastoralists in the Modern World",
      ],
      "GEOGRAPHY": [
        "India – Size and Location",
        "Physical Features of India",
        "Drainage",
        "Climate",
        "Natural Vegetation and Wildlife",
        "Population",
      ],
      "POLITICAL SCIENCE": [
        "What is Democracy? Why Democracy?",
        "Constitutional Design",
        "Electoral Politics",
        "Working of Institutions",
        "Democratic Rights",
      ],
      "ECONOMICS": [
        "The Story of Village Palampur",
        "People as Resource",
        "Poverty as a Challenge",
        "Food Security in India",
      ],
      "ENGLISH": [
        "The Fun They Had",
        "The Sound of Music",
        "The Little Girl",
        "A Truly Beautiful Mind",
        "The Snake and the Mirror",
        "My Childhood",
        "Packing",
        "Reach for the Top",
        "The Bond of Love",
        "Kathmandu",
        "If I Were You",
      ],
    },
    "10": {
      "MATHEMATICS": [
        "Real Numbers",
        "Polynomials",
        "Pair of Linear Equations in Two Variables",
        "Quadratic Equations",
        "Arithmetic Progressions",
        "Triangles",
        "Coordinate Geometry",
        "Introduction to Trigonometry",
        "Some Applications of Trigonometry",
        "Circles",
        "Constructions",
        "Areas Related to Circles",
        "Surface Areas and Volumes",
        "Statistics",
        "Probability",
      ],
      "SCIENCE": [
        "Chemical Reactions and Equations",
        "Acids, Bases and Salts",
        "Metals and Non-metals",
        "Carbon and its Compounds",
        "Life Processes",
        "Control and Coordination",
        "How Do Organisms Reproduce",
        "Heredity and Evolution",
        "Light – Reflection and Refraction",
        "The Human Eye and the Colourful World",
        "Electricity",
        "Magnetic Effects of Electric Current",
        "Our Environment",
        "Sources of Energy",
      ],
      "HISTORY": [
        "The Rise of Nationalism in Europe",
        "Nationalism in India",
        "The Making of a Global World",
        "The Age of Industrialisation",
        "Print Culture and the Modern World",
      ],
      "GEOGRAPHY": [
        "Resources and Development",
        "Forest and Wildlife Resources",
        "Water Resources",
        "Agriculture",
        "Minerals and Energy Resources",
        "Manufacturing Industries",
        "Lifelines of National Economy",
      ],
      "POLITICAL SCIENCE": [
        "Power Sharing",
        "Federalism",
        "Gender, Religion and Caste",
        "Political Parties",
        "Outcomes of Democracy",
      ],
      "ECONOMICS": [
        "Development",
        "Sectors of the Indian Economy",
        "Money and Credit",
        "Globalisation and the Indian Economy",
        "Consumer Rights",
      ],
      "ENGLISH": [
        "A Letter to God",
        "Nelson Mandela: Long Walk to Freedom",
        "Two Stories about Flying",
        "From the Diary of Anne Frank",
        "Glimpses of India",
        "Mijbil the Otter",
        "Madam Rides the Bus",
        "The Sermon at Benares",
        "The Proposal",
      ],
    },
    "11": {
      "PHYSICS": [
        "Physical World and Measurement",
        "Kinematics",
        "Laws of Motion",
        "Work, Energy and Power",
        "Motion of System of Particles",
        "Gravitation",
        "Properties of Bulk Matter",
        "Thermodynamics",
        "Kinetic Theory",
        "Oscillations and Waves",
      ],
      "CHEMISTRY": [
        "Some Basic Concepts of Chemistry",
        "Structure of Atom",
        "States of Matter",
        "Thermodynamics",
        "Equilibrium",
        "Organic Chemistry – Basic Principles",
        "Hydrocarbons",
      ],
      "BIOLOGY": [
        "Diversity in Living World",
        "Structural Organisation in Animals and Plants",
        "Cell Structure and Function",
        "Plant Physiology",
        "Human Physiology",
      ],
      "ENGLISH": ["Hornbill", "Snapshots"],
    },
    "12": {
      "PHYSICS": [
        "Electrostatics",
        "Current Electricity",
        "Magnetic Effects of Current",
        "Electromagnetic Induction",
        "Alternating Current",
        "Electromagnetic Waves",
        "Ray Optics",
        "Wave Optics",
        "Dual Nature of Radiation and Matter",
        "Atoms",
        "Nuclei",
        "Semiconductor Electronics",
      ],
      "CHEMISTRY": [
        "Solid State",
        "Solutions",
        "Electrochemistry",
        "Chemical Kinetics",
        "Surface Chemistry",
        "p-Block Elements",
        "d and f Block Elements",
        "Coordination Compounds",
        "Haloalkanes and Haloarenes",
        "Alcohols, Phenols and Ethers",
        "Aldehydes, Ketones and Carboxylic Acids",
        "Amines",
        "Biomolecules",
        "Polymers",
        "Chemistry in Everyday Life",
      ],
      "BIOLOGY": [
        "Reproduction",
        "Genetics and Evolution",
        "Biology and Human Welfare",
        "Biotechnology",
        "Ecology and Environment",
      ],
      "ENGLISH": ["Flamingo", "Vistas"],
    },
  },

  ICSE: {
    "8": {
      "MATHEMATICS": [
        "Rational Numbers",
        "Exponents",
        "Squares and Square Roots",
        "Cubes and Cube Roots",
        "Algebraic Expressions",
        "Linear Equations",
        "algebraic identities",
        "time and work ",
        "perimeter and area",
        "volume and area",
        "Direct and Inverse variation direct",
        "constructions of quadrilaterals",
        "linear inequation",
        "Factorisation",
        "Ratio and Proportion",
        "Percentages",
        "Profit and Loss",
        "Simple Interest",
        "Polygons",
        "Quadrilaterals",
        "Mensuration",
        "Data Handling",
        "Graphs",
      ],
      "PHYSICS": [
        "Matter",
        "Physical Quantities and Measurement",
        "Force and Pressure",
        "Energy",
        "Light",
        "Heat",
        "Sound",
        "Electricity",
      ],
      "CHEMISTRY": [
        "Matter",
        "Physical and Chemical Changes",
        "Elements, Compounds and Mixtures",
        "Atomic Structure",
        "Chemical Reactions",
        "Hydrogen",
        "Water",
        "Carbon and its Compounds",
      ],
      "BIOLOGY": [
        "Plant Tissues",
        "Animal Tissues",
        "Transport in Plants",
        "Reproduction in Plants",
        "Reproduction in Animals",
        "Ecosystem",
        "Human Body Systems",
        "Health and Hygiene",
      ],
      "HISTORY & CIVICS": [
        "Indian Constitution",
        "Parliament",
        "Judiciary",
        "Revolt of 1857",
        "Colonial Rule in India",
      ],
      "GEOGRAPHY": ["Climate of India", "Resources", "Agriculture", "Industries"],
      "ENGLISH": ["Prose", "Poetry", "Grammar and Composition"],
    },
    "9": {
      "MATHEMATICS": [
        "Rational and Irrational Numbers",
        "Indices",
        "Algebraic Expressions",
        "Factorisation",
        "Linear Equations",
        "Expansions",
        "Coordinate Geometry",
        "Triangles",
        "Pythagoras Theorem",
        "Circles",
        "Mensuration",
        "Statistics",
        "Trigonometry",
      ],
      "PHYSICS": [
        "Measurements and Experimentation",
        "Motion",
        "Laws of Motion",
        "Fluids",
        "Heat",
        "Light",
        "Sound",
      ],
      "CHEMISTRY": [
        "Matter and its Composition",
        "Atomic Structure",
        "Periodic Table",
        "Chemical Bonding",
        "Study of Gases",
        "Acids, Bases and Salts",
      ],
      "BIOLOGY": [
        "Cell",
        "Tissues",
        "Diversity of Living Organisms",
        "Plant Physiology",
        "Human Physiology",
        "Health and Hygiene",
      ],
      "HISTORY & CIVICS": [
        "French Revolution",
        "Russian Revolution",
        "World Wars",
        "Indian Constitution",
      ],
      "GEOGRAPHY": ["Earth as a Planet", "Structure of the Earth", "Climate", "Resources"],
      "ENGLISH": ["Prose", "Poetry", "Drama", "Grammar and Composition"],
    },
    "10": {
      "MATHEMATICS": [
        "Quadratic Equations",
        "Linear Inequations",
        "Ratio and Proportion",
        "Matrices",
        "Arithmetic Progression",
        "Coordinate Geometry",
        "Similarity",
        "Trigonometry",
        "Heights and Distances",
        "Mensuration",
        "Probability",
        "Statistics",
      ],
      "PHYSICS": [
        "Force",
        "Work, Power and Energy",
        "Machines",
        "Refraction of Light",
        "Spectrum",
        "Sound",
        "Current Electricity",
        "Magnetism",
        "Electromagnetic Induction",
        "Radioactivity",
      ],
      "CHEMISTRY": [
        "Periodic Properties",
        "Chemical Bonding",
        "Acids, Bases and Salts",
        "Analytical Chemistry",
        "Metallurgy",
        "Organic Chemistry",
      ],
      "BIOLOGY": [
        "Cell Cycle",
        "Genetics",
        "Plant Physiology",
        "Human Anatomy and Physiology",
        "Population",
        "Environment",
      ],
      "HISTORY & CIVICS": [
        "First War of Independence",
        "Growth of Nationalism",
        "World Wars",
        "United Nations",
        "Union Legislature",
        "Union Executive",
        "Judiciary",
      ],
      "GEOGRAPHY": [
        "Map Work",
        "Climate",
        "Soil Resources",
        "Water Resources",
        "Natural Vegetation",
        "Mineral Resources",
        "Industries",
        "Transport",
        "Waste Management",
      ],
      "ENGLISH": ["Prose", "Poetry", "Drama – Merchant of Venice", "Grammar and Composition"],
    },
  },
};

